---
language: generic
sudo: required
services:
 - docker
before_install:
 - docker build -t crust/reactaws -f Dockerfile.dev .
script:
 - docker run -e CI=true crust/reactaws npm run test
git:
 - depth: 3
 - quiet: true
 - submodules: false