FROM node:10.16.3-alpine

ENV http_proxy "http://172.29.213.98:8080"
ENV https_proxy "http://172.29.213.98:8080"

RUN npm config set http_proxy "http://172.29.213.98:8080"
RUN npm config set https-proxy "http://172.29.213.98:8080"

RUN npm config get http_proxy
RUN npm config get https-proxy

WORKDIR . /App

COPY package.json .

RUN npm cache clean --force
RUN npm install
RUN npm rebuild node-sass
RUN npm install --save array-unique
#RUN npm config set strict-ssl false
#RUN npm cache clean -f
#RUN npm install -g n latest
#RUN n stable

COPY . .

EXPOSE 3000

CMD ["npm", "run", "start"]